// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CollectionEntry } from './CollectionEntry';
import type { PriceGuide } from './PriceGuide';

export type CollectionCard = {
  set_code: string;
  collector_number: string;
  language_code: string;
  foil: boolean;
  name: string;
  rarity_code: string;
  scryfall_id: string;
  /**
   * Front image, relative to the frontend (e.g. `/card-images/FDN_1_EN.webp?v=gatherer`);
   * `null` while the card's image is pending.
   */
  image_url: string | null;
  /**
   * Back image of a double-faced card, like `image_url`; `null` for a single-faced card.
   */
  image_back_url: string | null;
  /**
   * Present only when the card is owned by the authenticated user.
   */
  collection_entry: CollectionEntry | null;
  /**
   * Number of distinct users actually offering this card to trade (search mode only) —
   * after applying each owner's visibility, trade binder selection and rarity filters. A
   * card no one offers anymore never appears in search results at all.
   */
  owner_count: number | null;
  /**
   * `true` if this card is engaged in an `ONE_ACCEPTED` or `FULLY_ACCEPTED` trade of its
   * owner (the authenticated user in collection mode, or the `player_username`-filtered
   * owner in search mode). Always `false` in the unscoped multi-owner search, where no
   * single owner can be attributed.
   */
  reserved: boolean;
  price_guide: PriceGuide | null;
};
