// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TradeStatusParam } from './TradeStatusParam';

export type ListTradesParams = {
  page: number;
  page_size: number;
  /**
   * Status filter, repeated for multiple values (e.g. `?status=PENDING&status=CLOSED`)
   */
  status: Array<TradeStatusParam>;
};
