// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RarityFilter } from './RarityFilter';

export type RarityFilters = { rarities: Array<RarityFilter> };
