// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RateTradeRequest = {
  /**
   * Rating given to the other party, from 0 to 5 inclusive.
   */
  rating: number;
};
