// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RemoveTradeCardRequest = {
  set_code: string;
  collector_number: string;
  language_code: string;
  foil: boolean;
  owner_username: string;
};
