// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Scope of the search whose set facet is requested: the same `q` / `player_username` as
 * `GET /search/card`, without its filters.
 */
export type SearchSetsParams = {
  q?: string;
  /**
   * Exact username of the owner to scope to (case-insensitive, no partial match)
   */
  player_username?: string;
};
