// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SetRarityFilterRequest = {
  rarity: string;
  is_open: boolean;
  /**
   * Signed so out-of-range values (e.g. negative) fail domain validation with a clean 400
   * instead of being rejected by the JSON extractor as a 422 before reaching the handler.
   */
  kept_copies: number;
};
