// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CardOffer = {
  owner_username: string;
  quantity: number;
  selling_price: number | null;
  /**
   * `true` if this exact copy is engaged in one of the owner's trades in `ONE_ACCEPTED` or
   * `FULLY_ACCEPTED` status — it cannot be traded away right now.
   */
  reserved: boolean;
};
