// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardImportLineError } from './CardImportLineError';

export type CardImport = {
  id: string;
  /**
   * `pending`, `running`, `completed` or `failed`.
   */
  status: string;
  /**
   * Data lines read from the CSV, before the "Tokens" set filter and deduplication.
   */
  source_lines: number;
  /**
   * Cards to write, after deduplication — the denominator for `processed_lines`.
   */
  total_lines: number;
  processed_lines: number;
  /**
   * Truncated to at most 100 entries; `error_count` carries the true total.
   */
  errors: Array<CardImportLineError>;
  error_count: number;
  error_message: string | null;
  /**
   * RFC 3339 timestamp
   */
  created_at: string;
  /**
   * RFC 3339 timestamp
   */
  finished_at: string | null;
};
