// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CardOffer = {
  owner_username: string;
  /**
   * Quantity this owner actually offers to trade — after applying their collection
   * visibility, trade binder selection and rarity filters. Never the raw quantity they own:
   * an owner offering `0` never appears in the list.
   */
  quantity: number;
  selling_price: number | null;
  /**
   * `true` if this exact copy is engaged in one of the owner's trades in `ONE_ACCEPTED` or
   * `FULLY_ACCEPTED` status — it cannot be traded away right now.
   */
  reserved: boolean;
};
