// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Params for `/card/{scryfall_id}/price-history`. Unlike [`PriceHistoryParams`], `foil` is
 * required: the catalog doesn't know a card's finish, so the caller must say which series
 * (normal or foil) it wants.
 */
export type CardPriceHistoryParams = {
  foil: boolean;
  /**
   * ISO 8601 date string (YYYY-MM-DD)
   */
  start_date?: string;
  /**
   * ISO 8601 date string (YYYY-MM-DD)
   */
  end_date?: string;
};
