// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Body of every error response. `error` is a technical message, for diagnosis only; clients
 * translate `code` into what they show the user (ADR 0018).
 */
export type ErrorResponse = {
  /**
   * Technical message, in English — never shown to the user as is.
   */
  error: string;
  /**
   * Stable snake_case identifier of the error (e.g. `binder_export`, `internal`).
   */
  code: string;
};
