// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TradeSummary } from './TradeSummary';

export type PaginatedTrades = {
  items: Array<TradeSummary>;
  total: number;
  page: number;
  page_size: number;
};
