// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RarityFilter = {
  rarity: string;
  is_open: boolean;
  kept_copies: number;
  copies: number;
  proposed: number;
};
