// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Global platform statistics, public.
 */
export type Stats = {
  /**
   * Number of Cards known to the platform.
   */
  card_number: number;
  /**
   * Number of Cardmarket prices recorded.
   */
  card_price_number: number;
  /**
   * Database size, in MB.
   */
  db_size_mb: number;
  /**
   * ISO 8601 date string (YYYY-MM-DD) of the most recent Cardmarket price — prices are dated
   * to the day. `null` until a price has been imported.
   */
  last_price_date: string | null;
};
