// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TradeCard } from './TradeCard';
import type { TradePartyState } from './TradePartyState';

export type TradeDetail = {
  id: string;
  status: string;
  partner_username: string;
  my_cards: Array<TradeCard>;
  partner_cards: Array<TradeCard>;
  me: TradePartyState;
  partner: TradePartyState;
};
