// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PriceGuide } from './PriceGuide';

/**
 * One card offered in a trade, from either side. Which side it's on is conveyed by which of
 * `TradeDetailResponse::my_cards`/`partner_cards` it's found in, not by a field here.
 */
export type TradeCard = {
  set_code: string;
  collector_number: string;
  language_code: string;
  foil: boolean;
  name: string;
  quantity: number;
  price_guide: PriceGuide | null;
  scryfall_id: string;
  the_gatherer_id: string | null;
};
