// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TradeSummary = {
  id: string;
  status: string;
  partner_username: string;
  my_card_count: number;
  partner_card_count: number;
  /**
   * RFC 3339 timestamp
   */
  updated_at: string;
};
