// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One party's acceptance/confirmation/rating state, already resolved from the caller's point
 * of view (`me` vs `partner`) — see `TradeDetailResponse`.
 */
export type TradePartyState = { accepted: boolean; confirmed: boolean; rating: number | null };
