// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserSuggestion = {
  username: string;
  /**
   * Always 5 — hardcoded display value, not backed by any stored rating yet.
   */
  note: number;
  card_count: number;
};
