// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A suggested user only appears if they offer at least one card to trade — a `private` user,
 * or one offering nothing under their current visibility/binders/rarity filters, is never
 * suggested.
 */
export type UserSuggestion = {
  username: string;
  /**
   * Always 5 — hardcoded display value, not backed by any stored rating yet.
   */
  note: number;
  /**
   * Sum of the quantities this user actually offers to trade across their whole collection —
   * not their total collection size.
   */
  card_count: number;
};
