// Generated by swift-openapi-generator, do not modify.
@_spi(Generated) public import OpenAPIRuntime
#if os(Linux)
@preconcurrency public import struct Foundation.URL
@preconcurrency public import struct Foundation.Data
@preconcurrency public import struct Foundation.Date
#else
public import struct Foundation.URL
public import struct Foundation.Data
public import struct Foundation.Date
#endif
/// A type that performs HTTP operations defined by the OpenAPI document.
public protocol APIProtocol: Sendable {
    /// - Remark: HTTP `GET /autocomplete/user`.
    /// - Remark: Generated from `#/paths//autocomplete/user/get(autocomplete_user)`.
    func autocomplete_user(_ input: Operations.autocomplete_user.Input) async throws -> Operations.autocomplete_user.Output
    /// - Remark: HTTP `POST /card/card-info`.
    /// - Remark: Generated from `#/paths//card/card-info/post(get_card_info)`.
    func get_card_info(_ input: Operations.get_card_info.Input) async throws -> Operations.get_card_info.Output
    /// - Remark: HTTP `GET /card/offers`.
    /// - Remark: Generated from `#/paths//card/offers/get(get_card_offers)`.
    func get_card_offers(_ input: Operations.get_card_offers.Input) async throws -> Operations.get_card_offers.Output
    /// - Remark: HTTP `GET /card/{scryfall_id}/price-history`.
    /// - Remark: Generated from `#/paths//card/{scryfall_id}/price-history/get(get_card_price_history)`.
    func get_card_price_history(_ input: Operations.get_card_price_history.Input) async throws -> Operations.get_card_price_history.Output
    /// - Remark: HTTP `GET /collection`.
    /// - Remark: Generated from `#/paths//collection/get(get_collection)`.
    func get_collection(_ input: Operations.get_collection.Input) async throws -> Operations.get_collection.Output
    /// - Remark: HTTP `POST /collection/import`.
    /// - Remark: Generated from `#/paths//collection/import/post(import_cards)`.
    func import_cards(_ input: Operations.import_cards.Input) async throws -> Operations.import_cards.Output
    /// - Remark: HTTP `GET /collection/price-history`.
    /// - Remark: Generated from `#/paths//collection/price-history/get(get_collection_price_history)`.
    func get_collection_price_history(_ input: Operations.get_collection_price_history.Input) async throws -> Operations.get_collection_price_history.Output
    /// - Remark: HTTP `GET /collection/stats`.
    /// - Remark: Generated from `#/paths//collection/stats/get(get_collection_stats)`.
    func get_collection_stats(_ input: Operations.get_collection_stats.Input) async throws -> Operations.get_collection_stats.Output
    /// - Remark: HTTP `GET /collection/visibility/rarities`.
    /// - Remark: Generated from `#/paths//collection/visibility/rarities/get(get_rarity_filters)`.
    func get_rarity_filters(_ input: Operations.get_rarity_filters.Input) async throws -> Operations.get_rarity_filters.Output
    /// - Remark: HTTP `POST /collection/visibility/rarities`.
    /// - Remark: Generated from `#/paths//collection/visibility/rarities/post(set_rarity_filter)`.
    func set_rarity_filter(_ input: Operations.set_rarity_filter.Input) async throws -> Operations.set_rarity_filter.Output
    /// - Remark: HTTP `GET /maintenance/stats`.
    /// - Remark: Generated from `#/paths//maintenance/stats/get(get_stats)`.
    func get_stats(_ input: Operations.get_stats.Input) async throws -> Operations.get_stats.Output
    /// - Remark: HTTP `POST /maintenance/trigger-price-update`.
    /// - Remark: Generated from `#/paths//maintenance/trigger-price-update/post(trigger_price_update)`.
    func trigger_price_update(_ input: Operations.trigger_price_update.Input) async throws -> Operations.trigger_price_update.Output
    /// - Remark: HTTP `POST /maintenance/update-cardmarket-ids`.
    /// - Remark: Generated from `#/paths//maintenance/update-cardmarket-ids/post(update_cardmarket_ids)`.
    func update_cardmarket_ids(_ input: Operations.update_cardmarket_ids.Input) async throws -> Operations.update_cardmarket_ids.Output
    /// - Remark: HTTP `GET /search/card`.
    /// - Remark: Generated from `#/paths//search/card/get(search_cards)`.
    func search_cards(_ input: Operations.search_cards.Input) async throws -> Operations.search_cards.Output
    /// - Remark: HTTP `GET /trades`.
    /// - Remark: Generated from `#/paths//trades/get(list_trades)`.
    func list_trades(_ input: Operations.list_trades.Input) async throws -> Operations.list_trades.Output
    /// - Remark: HTTP `POST /trades`.
    /// - Remark: Generated from `#/paths//trades/post(create_trade)`.
    func create_trade(_ input: Operations.create_trade.Input) async throws -> Operations.create_trade.Output
    /// - Remark: HTTP `GET /trades/{trade_id}`.
    /// - Remark: Generated from `#/paths//trades/{trade_id}/get(get_trade)`.
    func get_trade(_ input: Operations.get_trade.Input) async throws -> Operations.get_trade.Output
    /// - Remark: HTTP `POST /trades/{trade_id}/abandon`.
    /// - Remark: Generated from `#/paths//trades/{trade_id}/abandon/post(abandon_trade)`.
    func abandon_trade(_ input: Operations.abandon_trade.Input) async throws -> Operations.abandon_trade.Output
    /// - Remark: HTTP `POST /trades/{trade_id}/accept`.
    /// - Remark: Generated from `#/paths//trades/{trade_id}/accept/post(accept_trade)`.
    func accept_trade(_ input: Operations.accept_trade.Input) async throws -> Operations.accept_trade.Output
    /// - Remark: HTTP `POST /trades/{trade_id}/cards`.
    /// - Remark: Generated from `#/paths//trades/{trade_id}/cards/post(add_trade_card)`.
    func add_trade_card(_ input: Operations.add_trade_card.Input) async throws -> Operations.add_trade_card.Output
    /// - Remark: HTTP `POST /trades/{trade_id}/cards/remove`.
    /// - Remark: Generated from `#/paths//trades/{trade_id}/cards/remove/post(remove_trade_card)`.
    func remove_trade_card(_ input: Operations.remove_trade_card.Input) async throws -> Operations.remove_trade_card.Output
    /// - Remark: HTTP `POST /trades/{trade_id}/confirm`.
    /// - Remark: Generated from `#/paths//trades/{trade_id}/confirm/post(confirm_trade)`.
    func confirm_trade(_ input: Operations.confirm_trade.Input) async throws -> Operations.confirm_trade.Output
    /// - Remark: HTTP `POST /trades/{trade_id}/rate`.
    /// - Remark: Generated from `#/paths//trades/{trade_id}/rate/post(rate_trade)`.
    func rate_trade(_ input: Operations.rate_trade.Input) async throws -> Operations.rate_trade.Output
    /// - Remark: HTTP `POST /user`.
    /// - Remark: Generated from `#/paths//user/post(register)`.
    func register(_ input: Operations.register.Input) async throws -> Operations.register.Output
    /// - Remark: HTTP `GET /user/trade-binders`.
    /// - Remark: Generated from `#/paths//user/trade-binders/get(get_trade_binders)`.
    func get_trade_binders(_ input: Operations.get_trade_binders.Input) async throws -> Operations.get_trade_binders.Output
    /// - Remark: HTTP `POST /user/trade-binders`.
    /// - Remark: Generated from `#/paths//user/trade-binders/post(add_trade_binder)`.
    func add_trade_binder(_ input: Operations.add_trade_binder.Input) async throws -> Operations.add_trade_binder.Output
    /// - Remark: HTTP `DELETE /user/trade-binders/{name}`.
    /// - Remark: Generated from `#/paths//user/trade-binders/{name}/delete(remove_trade_binder)`.
    func remove_trade_binder(_ input: Operations.remove_trade_binder.Input) async throws -> Operations.remove_trade_binder.Output
    /// - Remark: HTTP `GET /user/visibility`.
    /// - Remark: Generated from `#/paths//user/visibility/get(get_visibility)`.
    func get_visibility(_ input: Operations.get_visibility.Input) async throws -> Operations.get_visibility.Output
    /// - Remark: HTTP `PUT /user/visibility`.
    /// - Remark: Generated from `#/paths//user/visibility/put(set_visibility)`.
    func set_visibility(_ input: Operations.set_visibility.Input) async throws -> Operations.set_visibility.Output
    /// - Remark: HTTP `GET /user/{username}`.
    /// - Remark: Generated from `#/paths//user/{username}/get(get_user_profile)`.
    func get_user_profile(_ input: Operations.get_user_profile.Input) async throws -> Operations.get_user_profile.Output
}

/// Convenience overloads for operation inputs.
extension APIProtocol {
    /// - Remark: HTTP `GET /autocomplete/user`.
    /// - Remark: Generated from `#/paths//autocomplete/user/get(autocomplete_user)`.
    public func autocomplete_user(
        query: Operations.autocomplete_user.Input.Query = .init(),
        headers: Operations.autocomplete_user.Input.Headers = .init()
    ) async throws -> Operations.autocomplete_user.Output {
        try await autocomplete_user(Operations.autocomplete_user.Input(
            query: query,
            headers: headers
        ))
    }
    /// - Remark: HTTP `POST /card/card-info`.
    /// - Remark: Generated from `#/paths//card/card-info/post(get_card_info)`.
    public func get_card_info() async throws -> Operations.get_card_info.Output {
        try await get_card_info(Operations.get_card_info.Input())
    }
    /// - Remark: HTTP `GET /card/offers`.
    /// - Remark: Generated from `#/paths//card/offers/get(get_card_offers)`.
    public func get_card_offers(
        query: Operations.get_card_offers.Input.Query,
        headers: Operations.get_card_offers.Input.Headers = .init()
    ) async throws -> Operations.get_card_offers.Output {
        try await get_card_offers(Operations.get_card_offers.Input(
            query: query,
            headers: headers
        ))
    }
    /// - Remark: HTTP `GET /card/{scryfall_id}/price-history`.
    /// - Remark: Generated from `#/paths//card/{scryfall_id}/price-history/get(get_card_price_history)`.
    public func get_card_price_history(
        path: Operations.get_card_price_history.Input.Path,
        query: Operations.get_card_price_history.Input.Query = .init(),
        headers: Operations.get_card_price_history.Input.Headers = .init()
    ) async throws -> Operations.get_card_price_history.Output {
        try await get_card_price_history(Operations.get_card_price_history.Input(
            path: path,
            query: query,
            headers: headers
        ))
    }
    /// - Remark: HTTP `GET /collection`.
    /// - Remark: Generated from `#/paths//collection/get(get_collection)`.
    public func get_collection(
        query: Operations.get_collection.Input.Query = .init(),
        headers: Operations.get_collection.Input.Headers = .init()
    ) async throws -> Operations.get_collection.Output {
        try await get_collection(Operations.get_collection.Input(
            query: query,
            headers: headers
        ))
    }
    /// - Remark: HTTP `POST /collection/import`.
    /// - Remark: Generated from `#/paths//collection/import/post(import_cards)`.
    public func import_cards(
        headers: Operations.import_cards.Input.Headers = .init(),
        body: Operations.import_cards.Input.Body
    ) async throws -> Operations.import_cards.Output {
        try await import_cards(Operations.import_cards.Input(
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `GET /collection/price-history`.
    /// - Remark: Generated from `#/paths//collection/price-history/get(get_collection_price_history)`.
    public func get_collection_price_history(
        query: Operations.get_collection_price_history.Input.Query = .init(),
        headers: Operations.get_collection_price_history.Input.Headers = .init()
    ) async throws -> Operations.get_collection_price_history.Output {
        try await get_collection_price_history(Operations.get_collection_price_history.Input(
            query: query,
            headers: headers
        ))
    }
    /// - Remark: HTTP `GET /collection/stats`.
    /// - Remark: Generated from `#/paths//collection/stats/get(get_collection_stats)`.
    public func get_collection_stats(headers: Operations.get_collection_stats.Input.Headers = .init()) async throws -> Operations.get_collection_stats.Output {
        try await get_collection_stats(Operations.get_collection_stats.Input(headers: headers))
    }
    /// - Remark: HTTP `GET /collection/visibility/rarities`.
    /// - Remark: Generated from `#/paths//collection/visibility/rarities/get(get_rarity_filters)`.
    public func get_rarity_filters(headers: Operations.get_rarity_filters.Input.Headers = .init()) async throws -> Operations.get_rarity_filters.Output {
        try await get_rarity_filters(Operations.get_rarity_filters.Input(headers: headers))
    }
    /// - Remark: HTTP `POST /collection/visibility/rarities`.
    /// - Remark: Generated from `#/paths//collection/visibility/rarities/post(set_rarity_filter)`.
    public func set_rarity_filter(body: Operations.set_rarity_filter.Input.Body) async throws -> Operations.set_rarity_filter.Output {
        try await set_rarity_filter(Operations.set_rarity_filter.Input(body: body))
    }
    /// - Remark: HTTP `GET /maintenance/stats`.
    /// - Remark: Generated from `#/paths//maintenance/stats/get(get_stats)`.
    public func get_stats(headers: Operations.get_stats.Input.Headers = .init()) async throws -> Operations.get_stats.Output {
        try await get_stats(Operations.get_stats.Input(headers: headers))
    }
    /// - Remark: HTTP `POST /maintenance/trigger-price-update`.
    /// - Remark: Generated from `#/paths//maintenance/trigger-price-update/post(trigger_price_update)`.
    public func trigger_price_update() async throws -> Operations.trigger_price_update.Output {
        try await trigger_price_update(Operations.trigger_price_update.Input())
    }
    /// - Remark: HTTP `POST /maintenance/update-cardmarket-ids`.
    /// - Remark: Generated from `#/paths//maintenance/update-cardmarket-ids/post(update_cardmarket_ids)`.
    public func update_cardmarket_ids(headers: Operations.update_cardmarket_ids.Input.Headers = .init()) async throws -> Operations.update_cardmarket_ids.Output {
        try await update_cardmarket_ids(Operations.update_cardmarket_ids.Input(headers: headers))
    }
    /// - Remark: HTTP `GET /search/card`.
    /// - Remark: Generated from `#/paths//search/card/get(search_cards)`.
    public func search_cards(
        query: Operations.search_cards.Input.Query = .init(),
        headers: Operations.search_cards.Input.Headers = .init()
    ) async throws -> Operations.search_cards.Output {
        try await search_cards(Operations.search_cards.Input(
            query: query,
            headers: headers
        ))
    }
    /// - Remark: HTTP `GET /trades`.
    /// - Remark: Generated from `#/paths//trades/get(list_trades)`.
    public func list_trades(
        query: Operations.list_trades.Input.Query = .init(),
        headers: Operations.list_trades.Input.Headers = .init()
    ) async throws -> Operations.list_trades.Output {
        try await list_trades(Operations.list_trades.Input(
            query: query,
            headers: headers
        ))
    }
    /// - Remark: HTTP `POST /trades`.
    /// - Remark: Generated from `#/paths//trades/post(create_trade)`.
    public func create_trade(
        headers: Operations.create_trade.Input.Headers = .init(),
        body: Operations.create_trade.Input.Body
    ) async throws -> Operations.create_trade.Output {
        try await create_trade(Operations.create_trade.Input(
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `GET /trades/{trade_id}`.
    /// - Remark: Generated from `#/paths//trades/{trade_id}/get(get_trade)`.
    public func get_trade(
        path: Operations.get_trade.Input.Path,
        headers: Operations.get_trade.Input.Headers = .init()
    ) async throws -> Operations.get_trade.Output {
        try await get_trade(Operations.get_trade.Input(
            path: path,
            headers: headers
        ))
    }
    /// - Remark: HTTP `POST /trades/{trade_id}/abandon`.
    /// - Remark: Generated from `#/paths//trades/{trade_id}/abandon/post(abandon_trade)`.
    public func abandon_trade(path: Operations.abandon_trade.Input.Path) async throws -> Operations.abandon_trade.Output {
        try await abandon_trade(Operations.abandon_trade.Input(path: path))
    }
    /// - Remark: HTTP `POST /trades/{trade_id}/accept`.
    /// - Remark: Generated from `#/paths//trades/{trade_id}/accept/post(accept_trade)`.
    public func accept_trade(path: Operations.accept_trade.Input.Path) async throws -> Operations.accept_trade.Output {
        try await accept_trade(Operations.accept_trade.Input(path: path))
    }
    /// - Remark: HTTP `POST /trades/{trade_id}/cards`.
    /// - Remark: Generated from `#/paths//trades/{trade_id}/cards/post(add_trade_card)`.
    public func add_trade_card(
        path: Operations.add_trade_card.Input.Path,
        body: Operations.add_trade_card.Input.Body
    ) async throws -> Operations.add_trade_card.Output {
        try await add_trade_card(Operations.add_trade_card.Input(
            path: path,
            body: body
        ))
    }
    /// - Remark: HTTP `POST /trades/{trade_id}/cards/remove`.
    /// - Remark: Generated from `#/paths//trades/{trade_id}/cards/remove/post(remove_trade_card)`.
    public func remove_trade_card(
        path: Operations.remove_trade_card.Input.Path,
        body: Operations.remove_trade_card.Input.Body
    ) async throws -> Operations.remove_trade_card.Output {
        try await remove_trade_card(Operations.remove_trade_card.Input(
            path: path,
            body: body
        ))
    }
    /// - Remark: HTTP `POST /trades/{trade_id}/confirm`.
    /// - Remark: Generated from `#/paths//trades/{trade_id}/confirm/post(confirm_trade)`.
    public func confirm_trade(path: Operations.confirm_trade.Input.Path) async throws -> Operations.confirm_trade.Output {
        try await confirm_trade(Operations.confirm_trade.Input(path: path))
    }
    /// - Remark: HTTP `POST /trades/{trade_id}/rate`.
    /// - Remark: Generated from `#/paths//trades/{trade_id}/rate/post(rate_trade)`.
    public func rate_trade(
        path: Operations.rate_trade.Input.Path,
        body: Operations.rate_trade.Input.Body
    ) async throws -> Operations.rate_trade.Output {
        try await rate_trade(Operations.rate_trade.Input(
            path: path,
            body: body
        ))
    }
    /// - Remark: HTTP `POST /user`.
    /// - Remark: Generated from `#/paths//user/post(register)`.
    public func register() async throws -> Operations.register.Output {
        try await register(Operations.register.Input())
    }
    /// - Remark: HTTP `GET /user/trade-binders`.
    /// - Remark: Generated from `#/paths//user/trade-binders/get(get_trade_binders)`.
    public func get_trade_binders(headers: Operations.get_trade_binders.Input.Headers = .init()) async throws -> Operations.get_trade_binders.Output {
        try await get_trade_binders(Operations.get_trade_binders.Input(headers: headers))
    }
    /// - Remark: HTTP `POST /user/trade-binders`.
    /// - Remark: Generated from `#/paths//user/trade-binders/post(add_trade_binder)`.
    public func add_trade_binder(body: Operations.add_trade_binder.Input.Body) async throws -> Operations.add_trade_binder.Output {
        try await add_trade_binder(Operations.add_trade_binder.Input(body: body))
    }
    /// - Remark: HTTP `DELETE /user/trade-binders/{name}`.
    /// - Remark: Generated from `#/paths//user/trade-binders/{name}/delete(remove_trade_binder)`.
    public func remove_trade_binder(path: Operations.remove_trade_binder.Input.Path) async throws -> Operations.remove_trade_binder.Output {
        try await remove_trade_binder(Operations.remove_trade_binder.Input(path: path))
    }
    /// - Remark: HTTP `GET /user/visibility`.
    /// - Remark: Generated from `#/paths//user/visibility/get(get_visibility)`.
    public func get_visibility(headers: Operations.get_visibility.Input.Headers = .init()) async throws -> Operations.get_visibility.Output {
        try await get_visibility(Operations.get_visibility.Input(headers: headers))
    }
    /// - Remark: HTTP `PUT /user/visibility`.
    /// - Remark: Generated from `#/paths//user/visibility/put(set_visibility)`.
    public func set_visibility(body: Operations.set_visibility.Input.Body) async throws -> Operations.set_visibility.Output {
        try await set_visibility(Operations.set_visibility.Input(body: body))
    }
    /// - Remark: HTTP `GET /user/{username}`.
    /// - Remark: Generated from `#/paths//user/{username}/get(get_user_profile)`.
    public func get_user_profile(
        path: Operations.get_user_profile.Input.Path,
        headers: Operations.get_user_profile.Input.Headers = .init()
    ) async throws -> Operations.get_user_profile.Output {
        try await get_user_profile(Operations.get_user_profile.Input(
            path: path,
            headers: headers
        ))
    }
}

/// Server URLs defined in the OpenAPI document.
public enum Servers {}
