// Generated by swift-openapi-generator, do not modify.
@_spi(Generated) public import OpenAPIRuntime
#if os(Linux)
@preconcurrency public import struct Foundation.URL
@preconcurrency public import struct Foundation.Data
@preconcurrency public import struct Foundation.Date
#else
public import struct Foundation.URL
public import struct Foundation.Data
public import struct Foundation.Date
#endif
extension Components {
    /// Types generated from the `#/components/schemas` section of the OpenAPI document.
    public enum Schemas {
        /// - Remark: Generated from `#/components/schemas/AddTradeBinderRequest`.
        public struct AddTradeBinderRequest: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/AddTradeBinderRequest/binder_name`.
            public var binder_name: Swift.String
            /// Creates a new `AddTradeBinderRequest`.
            ///
            /// - Parameters:
            ///   - binder_name:
            public init(binder_name: Swift.String) {
                self.binder_name = binder_name
            }
            public enum CodingKeys: String, CodingKey {
                case binder_name
            }
        }
        /// - Remark: Generated from `#/components/schemas/AddTradeCardRequest`.
        public struct AddTradeCardRequest: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/AddTradeCardRequest/collector_number`.
            public var collector_number: Swift.String
            /// - Remark: Generated from `#/components/schemas/AddTradeCardRequest/foil`.
            public var foil: Swift.Bool
            /// - Remark: Generated from `#/components/schemas/AddTradeCardRequest/language_code`.
            public var language_code: Swift.String
            /// - Remark: Generated from `#/components/schemas/AddTradeCardRequest/owner_username`.
            public var owner_username: Swift.String
            /// - Remark: Generated from `#/components/schemas/AddTradeCardRequest/quantity`.
            public var quantity: Swift.Int32
            /// - Remark: Generated from `#/components/schemas/AddTradeCardRequest/set_code`.
            public var set_code: Swift.String
            /// Creates a new `AddTradeCardRequest`.
            ///
            /// - Parameters:
            ///   - collector_number:
            ///   - foil:
            ///   - language_code:
            ///   - owner_username:
            ///   - quantity:
            ///   - set_code:
            public init(
                collector_number: Swift.String,
                foil: Swift.Bool,
                language_code: Swift.String,
                owner_username: Swift.String,
                quantity: Swift.Int32,
                set_code: Swift.String
            ) {
                self.collector_number = collector_number
                self.foil = foil
                self.language_code = language_code
                self.owner_username = owner_username
                self.quantity = quantity
                self.set_code = set_code
            }
            public enum CodingKeys: String, CodingKey {
                case collector_number
                case foil
                case language_code
                case owner_username
                case quantity
                case set_code
            }
        }
        /// - Remark: Generated from `#/components/schemas/BinderInfoResponse`.
        public struct BinderInfoResponse: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/BinderInfoResponse/card_count`.
            public var card_count: Swift.Int64
            /// - Remark: Generated from `#/components/schemas/BinderInfoResponse/name`.
            public var name: Swift.String
            /// Creates a new `BinderInfoResponse`.
            ///
            /// - Parameters:
            ///   - card_count:
            ///   - name:
            public init(
                card_count: Swift.Int64,
                name: Swift.String
            ) {
                self.card_count = card_count
                self.name = name
            }
            public enum CodingKeys: String, CodingKey {
                case card_count
                case name
            }
        }
        /// - Remark: Generated from `#/components/schemas/CardOfferResponse`.
        public struct CardOfferResponse: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/CardOfferResponse/owner_username`.
            public var owner_username: Swift.String
            /// Quantity this owner actually offers to trade — after applying their collection
            /// visibility, trade binder selection and rarity filters. Never the raw quantity they own:
            /// an owner offering `0` never appears in the list.
            ///
            /// - Remark: Generated from `#/components/schemas/CardOfferResponse/quantity`.
            public var quantity: Swift.Int32
            /// `true` if this exact copy is engaged in one of the owner's trades in `ONE_ACCEPTED` or
            /// `FULLY_ACCEPTED` status — it cannot be traded away right now.
            ///
            /// - Remark: Generated from `#/components/schemas/CardOfferResponse/reserved`.
            public var reserved: Swift.Bool
            /// - Remark: Generated from `#/components/schemas/CardOfferResponse/selling_price`.
            public var selling_price: Swift.Int32?
            /// Creates a new `CardOfferResponse`.
            ///
            /// - Parameters:
            ///   - owner_username:
            ///   - quantity: Quantity this owner actually offers to trade — after applying their collection
            ///   - reserved: `true` if this exact copy is engaged in one of the owner's trades in `ONE_ACCEPTED` or
            ///   - selling_price:
            public init(
                owner_username: Swift.String,
                quantity: Swift.Int32,
                reserved: Swift.Bool,
                selling_price: Swift.Int32? = nil
            ) {
                self.owner_username = owner_username
                self.quantity = quantity
                self.reserved = reserved
                self.selling_price = selling_price
            }
            public enum CodingKeys: String, CodingKey {
                case owner_username
                case quantity
                case reserved
                case selling_price
            }
        }
        /// - Remark: Generated from `#/components/schemas/CardOffersSortByParam`.
        @frozen public enum CardOffersSortByParam: String, Codable, Hashable, Sendable, CaseIterable {
            case selling_price = "selling_price"
        }
        /// - Remark: Generated from `#/components/schemas/CollectionCardResponse`.
        public struct CollectionCardResponse: Codable, Hashable, Sendable {
            /// Present only when the card is owned by the authenticated user.
            ///
            /// - Remark: Generated from `#/components/schemas/CollectionCardResponse/collection_entry`.
            public var collection_entry: Components.Schemas.CollectionEntryResponse?
            /// - Remark: Generated from `#/components/schemas/CollectionCardResponse/collector_number`.
            public var collector_number: Swift.String
            /// - Remark: Generated from `#/components/schemas/CollectionCardResponse/foil`.
            public var foil: Swift.Bool
            /// - Remark: Generated from `#/components/schemas/CollectionCardResponse/language_code`.
            public var language_code: Swift.String
            /// - Remark: Generated from `#/components/schemas/CollectionCardResponse/name`.
            public var name: Swift.String
            /// Number of distinct users actually offering this card to trade (search mode only) —
            /// after applying each owner's visibility, trade binder selection and rarity filters. A
            /// card no one offers anymore never appears in search results at all.
            ///
            /// - Remark: Generated from `#/components/schemas/CollectionCardResponse/owner_count`.
            public var owner_count: Swift.Int64?
            /// - Remark: Generated from `#/components/schemas/CollectionCardResponse/price_guide`.
            public var price_guide: Components.Schemas.PriceGuideResponse?
            /// - Remark: Generated from `#/components/schemas/CollectionCardResponse/rarity_code`.
            public var rarity_code: Swift.String
            /// `true` if this card is engaged in an `ONE_ACCEPTED` or `FULLY_ACCEPTED` trade of its
            /// owner (the authenticated user in collection mode, or the `player_username`-filtered
            /// owner in search mode). Always `false` in the unscoped multi-owner search, where no
            /// single owner can be attributed.
            ///
            /// - Remark: Generated from `#/components/schemas/CollectionCardResponse/reserved`.
            public var reserved: Swift.Bool
            /// - Remark: Generated from `#/components/schemas/CollectionCardResponse/scryfall_id`.
            public var scryfall_id: Swift.String
            /// - Remark: Generated from `#/components/schemas/CollectionCardResponse/set_code`.
            public var set_code: Swift.String
            /// - Remark: Generated from `#/components/schemas/CollectionCardResponse/the_gatherer_id`.
            public var the_gatherer_id: Swift.String?
            /// Creates a new `CollectionCardResponse`.
            ///
            /// - Parameters:
            ///   - collection_entry: Present only when the card is owned by the authenticated user.
            ///   - collector_number:
            ///   - foil:
            ///   - language_code:
            ///   - name:
            ///   - owner_count: Number of distinct users actually offering this card to trade (search mode only) —
            ///   - price_guide:
            ///   - rarity_code:
            ///   - reserved: `true` if this card is engaged in an `ONE_ACCEPTED` or `FULLY_ACCEPTED` trade of its
            ///   - scryfall_id:
            ///   - set_code:
            ///   - the_gatherer_id:
            public init(
                collection_entry: Components.Schemas.CollectionEntryResponse? = nil,
                collector_number: Swift.String,
                foil: Swift.Bool,
                language_code: Swift.String,
                name: Swift.String,
                owner_count: Swift.Int64? = nil,
                price_guide: Components.Schemas.PriceGuideResponse? = nil,
                rarity_code: Swift.String,
                reserved: Swift.Bool,
                scryfall_id: Swift.String,
                set_code: Swift.String,
                the_gatherer_id: Swift.String? = nil
            ) {
                self.collection_entry = collection_entry
                self.collector_number = collector_number
                self.foil = foil
                self.language_code = language_code
                self.name = name
                self.owner_count = owner_count
                self.price_guide = price_guide
                self.rarity_code = rarity_code
                self.reserved = reserved
                self.scryfall_id = scryfall_id
                self.set_code = set_code
                self.the_gatherer_id = the_gatherer_id
            }
            public enum CodingKeys: String, CodingKey {
                case collection_entry
                case collector_number
                case foil
                case language_code
                case name
                case owner_count
                case price_guide
                case rarity_code
                case reserved
                case scryfall_id
                case set_code
                case the_gatherer_id
            }
        }
        /// - Remark: Generated from `#/components/schemas/CollectionEntryResponse`.
        public struct CollectionEntryResponse: Codable, Hashable, Sendable {
            /// RFC 3339 timestamp
            ///
            /// - Remark: Generated from `#/components/schemas/CollectionEntryResponse/added_at`.
            public var added_at: Swift.String
            /// - Remark: Generated from `#/components/schemas/CollectionEntryResponse/purchase_price`.
            public var purchase_price: Swift.Int32
            /// - Remark: Generated from `#/components/schemas/CollectionEntryResponse/quantity`.
            public var quantity: Swift.Int32
            /// Creates a new `CollectionEntryResponse`.
            ///
            /// - Parameters:
            ///   - added_at: RFC 3339 timestamp
            ///   - purchase_price:
            ///   - quantity:
            public init(
                added_at: Swift.String,
                purchase_price: Swift.Int32,
                quantity: Swift.Int32
            ) {
                self.added_at = added_at
                self.purchase_price = purchase_price
                self.quantity = quantity
            }
            public enum CodingKeys: String, CodingKey {
                case added_at
                case purchase_price
                case quantity
            }
        }
        /// - Remark: Generated from `#/components/schemas/CollectionStatsResponse`.
        public struct CollectionStatsResponse: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/CollectionStatsResponse/binders`.
            public var binders: [Components.Schemas.BinderInfoResponse]
            /// - Remark: Generated from `#/components/schemas/CollectionStatsResponse/price_trend_max`.
            public var price_trend_max: Swift.Int32?
            /// - Remark: Generated from `#/components/schemas/CollectionStatsResponse/price_trend_min`.
            public var price_trend_min: Swift.Int32?
            /// - Remark: Generated from `#/components/schemas/CollectionStatsResponse/sets`.
            public var sets: [Components.Schemas.SetInfoResponse]
            /// - Remark: Generated from `#/components/schemas/CollectionStatsResponse/total_cards`.
            public var total_cards: Swift.Int64
            /// - Remark: Generated from `#/components/schemas/CollectionStatsResponse/unique_cards`.
            public var unique_cards: Swift.Int64
            /// Creates a new `CollectionStatsResponse`.
            ///
            /// - Parameters:
            ///   - binders:
            ///   - price_trend_max:
            ///   - price_trend_min:
            ///   - sets:
            ///   - total_cards:
            ///   - unique_cards:
            public init(
                binders: [Components.Schemas.BinderInfoResponse],
                price_trend_max: Swift.Int32? = nil,
                price_trend_min: Swift.Int32? = nil,
                sets: [Components.Schemas.SetInfoResponse],
                total_cards: Swift.Int64,
                unique_cards: Swift.Int64
            ) {
                self.binders = binders
                self.price_trend_max = price_trend_max
                self.price_trend_min = price_trend_min
                self.sets = sets
                self.total_cards = total_cards
                self.unique_cards = unique_cards
            }
            public enum CodingKeys: String, CodingKey {
                case binders
                case price_trend_max
                case price_trend_min
                case sets
                case total_cards
                case unique_cards
            }
        }
        /// - Remark: Generated from `#/components/schemas/CollectionVisibilityParam`.
        @frozen public enum CollectionVisibilityParam: String, Codable, Hashable, Sendable, CaseIterable {
            case _public = "public"
            case trade = "trade"
            case _private = "private"
        }
        /// - Remark: Generated from `#/components/schemas/CreateTradeRequest`.
        public struct CreateTradeRequest: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/CreateTradeRequest/respondent_username`.
            public var respondent_username: Swift.String
            /// Creates a new `CreateTradeRequest`.
            ///
            /// - Parameters:
            ///   - respondent_username:
            public init(respondent_username: Swift.String) {
                self.respondent_username = respondent_username
            }
            public enum CodingKeys: String, CodingKey {
                case respondent_username
            }
        }
        /// - Remark: Generated from `#/components/schemas/CreateTradeResponse`.
        public struct CreateTradeResponse: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/CreateTradeResponse/id`.
            public var id: Swift.String
            /// Creates a new `CreateTradeResponse`.
            ///
            /// - Parameters:
            ///   - id:
            public init(id: Swift.String) {
                self.id = id
            }
            public enum CodingKeys: String, CodingKey {
                case id
            }
        }
        /// - Remark: Generated from `#/components/schemas/EnqueueResponse`.
        public struct EnqueueResponse: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/EnqueueResponse/enqueued`.
            public var enqueued: Swift.Int
            /// Creates a new `EnqueueResponse`.
            ///
            /// - Parameters:
            ///   - enqueued:
            public init(enqueued: Swift.Int) {
                self.enqueued = enqueued
            }
            public enum CodingKeys: String, CodingKey {
                case enqueued
            }
        }
        /// - Remark: Generated from `#/components/schemas/MessageResponse`.
        public struct MessageResponse: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/MessageResponse/message`.
            public var message: Swift.String
            /// Creates a new `MessageResponse`.
            ///
            /// - Parameters:
            ///   - message:
            public init(message: Swift.String) {
                self.message = message
            }
            public enum CodingKeys: String, CodingKey {
                case message
            }
        }
        /// - Remark: Generated from `#/components/schemas/PaginatedCardOffersResponse`.
        public struct PaginatedCardOffersResponse: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/PaginatedCardOffersResponse/items`.
            public var items: [Components.Schemas.CardOfferResponse]
            /// - Remark: Generated from `#/components/schemas/PaginatedCardOffersResponse/page`.
            public var page: Swift.Int32
            /// - Remark: Generated from `#/components/schemas/PaginatedCardOffersResponse/page_size`.
            public var page_size: Swift.Int32
            /// - Remark: Generated from `#/components/schemas/PaginatedCardOffersResponse/total`.
            public var total: Swift.Int64
            /// Creates a new `PaginatedCardOffersResponse`.
            ///
            /// - Parameters:
            ///   - items:
            ///   - page:
            ///   - page_size:
            ///   - total:
            public init(
                items: [Components.Schemas.CardOfferResponse],
                page: Swift.Int32,
                page_size: Swift.Int32,
                total: Swift.Int64
            ) {
                self.items = items
                self.page = page
                self.page_size = page_size
                self.total = total
            }
            public enum CodingKeys: String, CodingKey {
                case items
                case page
                case page_size
                case total
            }
        }
        /// - Remark: Generated from `#/components/schemas/PaginatedCollectionResponse`.
        public struct PaginatedCollectionResponse: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/PaginatedCollectionResponse/items`.
            public var items: [Components.Schemas.CollectionCardResponse]
            /// - Remark: Generated from `#/components/schemas/PaginatedCollectionResponse/page`.
            public var page: Swift.Int32
            /// - Remark: Generated from `#/components/schemas/PaginatedCollectionResponse/page_size`.
            public var page_size: Swift.Int32
            /// - Remark: Generated from `#/components/schemas/PaginatedCollectionResponse/total`.
            public var total: Swift.Int64
            /// Creates a new `PaginatedCollectionResponse`.
            ///
            /// - Parameters:
            ///   - items:
            ///   - page:
            ///   - page_size:
            ///   - total:
            public init(
                items: [Components.Schemas.CollectionCardResponse],
                page: Swift.Int32,
                page_size: Swift.Int32,
                total: Swift.Int64
            ) {
                self.items = items
                self.page = page
                self.page_size = page_size
                self.total = total
            }
            public enum CodingKeys: String, CodingKey {
                case items
                case page
                case page_size
                case total
            }
        }
        /// - Remark: Generated from `#/components/schemas/PaginatedTradesResponse`.
        public struct PaginatedTradesResponse: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/PaginatedTradesResponse/items`.
            public var items: [Components.Schemas.TradeSummaryResponse]
            /// - Remark: Generated from `#/components/schemas/PaginatedTradesResponse/page`.
            public var page: Swift.Int32
            /// - Remark: Generated from `#/components/schemas/PaginatedTradesResponse/page_size`.
            public var page_size: Swift.Int32
            /// - Remark: Generated from `#/components/schemas/PaginatedTradesResponse/total`.
            public var total: Swift.Int64
            /// Creates a new `PaginatedTradesResponse`.
            ///
            /// - Parameters:
            ///   - items:
            ///   - page:
            ///   - page_size:
            ///   - total:
            public init(
                items: [Components.Schemas.TradeSummaryResponse],
                page: Swift.Int32,
                page_size: Swift.Int32,
                total: Swift.Int64
            ) {
                self.items = items
                self.page = page
                self.page_size = page_size
                self.total = total
            }
            public enum CodingKeys: String, CodingKey {
                case items
                case page
                case page_size
                case total
            }
        }
        /// - Remark: Generated from `#/components/schemas/PriceGuideResponse`.
        public struct PriceGuideResponse: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/PriceGuideResponse/avg`.
            public var avg: Swift.Int32?
            /// - Remark: Generated from `#/components/schemas/PriceGuideResponse/low`.
            public var low: Swift.Int32?
            /// - Remark: Generated from `#/components/schemas/PriceGuideResponse/trend`.
            public var trend: Swift.Int32?
            /// Creates a new `PriceGuideResponse`.
            ///
            /// - Parameters:
            ///   - avg:
            ///   - low:
            ///   - trend:
            public init(
                avg: Swift.Int32? = nil,
                low: Swift.Int32? = nil,
                trend: Swift.Int32? = nil
            ) {
                self.avg = avg
                self.low = low
                self.trend = trend
            }
            public enum CodingKeys: String, CodingKey {
                case avg
                case low
                case trend
            }
        }
        /// - Remark: Generated from `#/components/schemas/PriceHistoryEntryResponse`.
        public struct PriceHistoryEntryResponse: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/PriceHistoryEntryResponse/avg`.
            public var avg: Swift.Int64
            /// ISO 8601 date string (YYYY-MM-DD)
            ///
            /// - Remark: Generated from `#/components/schemas/PriceHistoryEntryResponse/date`.
            public var date: Swift.String
            /// - Remark: Generated from `#/components/schemas/PriceHistoryEntryResponse/low`.
            public var low: Swift.Int64
            /// - Remark: Generated from `#/components/schemas/PriceHistoryEntryResponse/trend`.
            public var trend: Swift.Int64
            /// Creates a new `PriceHistoryEntryResponse`.
            ///
            /// - Parameters:
            ///   - avg:
            ///   - date: ISO 8601 date string (YYYY-MM-DD)
            ///   - low:
            ///   - trend:
            public init(
                avg: Swift.Int64,
                date: Swift.String,
                low: Swift.Int64,
                trend: Swift.Int64
            ) {
                self.avg = avg
                self.date = date
                self.low = low
                self.trend = trend
            }
            public enum CodingKeys: String, CodingKey {
                case avg
                case date
                case low
                case trend
            }
        }
        /// - Remark: Generated from `#/components/schemas/RarityCodeParam`.
        @frozen public enum RarityCodeParam: String, Codable, Hashable, Sendable, CaseIterable {
            case C = "C"
            case U = "U"
            case R = "R"
            case M = "M"
            case S = "S"
        }
        /// - Remark: Generated from `#/components/schemas/RarityFilterResponse`.
        public struct RarityFilterResponse: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/RarityFilterResponse/copies`.
            public var copies: Swift.Int64
            /// - Remark: Generated from `#/components/schemas/RarityFilterResponse/is_open`.
            public var is_open: Swift.Bool
            /// - Remark: Generated from `#/components/schemas/RarityFilterResponse/kept_copies`.
            public var kept_copies: Swift.Int32
            /// - Remark: Generated from `#/components/schemas/RarityFilterResponse/proposed`.
            public var proposed: Swift.Int64
            /// - Remark: Generated from `#/components/schemas/RarityFilterResponse/rarity`.
            public var rarity: Swift.String
            /// Creates a new `RarityFilterResponse`.
            ///
            /// - Parameters:
            ///   - copies:
            ///   - is_open:
            ///   - kept_copies:
            ///   - proposed:
            ///   - rarity:
            public init(
                copies: Swift.Int64,
                is_open: Swift.Bool,
                kept_copies: Swift.Int32,
                proposed: Swift.Int64,
                rarity: Swift.String
            ) {
                self.copies = copies
                self.is_open = is_open
                self.kept_copies = kept_copies
                self.proposed = proposed
                self.rarity = rarity
            }
            public enum CodingKeys: String, CodingKey {
                case copies
                case is_open
                case kept_copies
                case proposed
                case rarity
            }
        }
        /// - Remark: Generated from `#/components/schemas/RarityFiltersResponse`.
        public struct RarityFiltersResponse: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/RarityFiltersResponse/rarities`.
            public var rarities: [Components.Schemas.RarityFilterResponse]
            /// Creates a new `RarityFiltersResponse`.
            ///
            /// - Parameters:
            ///   - rarities:
            public init(rarities: [Components.Schemas.RarityFilterResponse]) {
                self.rarities = rarities
            }
            public enum CodingKeys: String, CodingKey {
                case rarities
            }
        }
        /// - Remark: Generated from `#/components/schemas/RateTradeRequest`.
        public struct RateTradeRequest: Codable, Hashable, Sendable {
            /// Rating given to the other party, from 0 to 5 inclusive.
            ///
            /// - Remark: Generated from `#/components/schemas/RateTradeRequest/rating`.
            public var rating: Swift.Int32
            /// Creates a new `RateTradeRequest`.
            ///
            /// - Parameters:
            ///   - rating: Rating given to the other party, from 0 to 5 inclusive.
            public init(rating: Swift.Int32) {
                self.rating = rating
            }
            public enum CodingKeys: String, CodingKey {
                case rating
            }
        }
        /// - Remark: Generated from `#/components/schemas/RemoveTradeCardRequest`.
        public struct RemoveTradeCardRequest: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/RemoveTradeCardRequest/collector_number`.
            public var collector_number: Swift.String
            /// - Remark: Generated from `#/components/schemas/RemoveTradeCardRequest/foil`.
            public var foil: Swift.Bool
            /// - Remark: Generated from `#/components/schemas/RemoveTradeCardRequest/language_code`.
            public var language_code: Swift.String
            /// - Remark: Generated from `#/components/schemas/RemoveTradeCardRequest/owner_username`.
            public var owner_username: Swift.String
            /// - Remark: Generated from `#/components/schemas/RemoveTradeCardRequest/set_code`.
            public var set_code: Swift.String
            /// Creates a new `RemoveTradeCardRequest`.
            ///
            /// - Parameters:
            ///   - collector_number:
            ///   - foil:
            ///   - language_code:
            ///   - owner_username:
            ///   - set_code:
            public init(
                collector_number: Swift.String,
                foil: Swift.Bool,
                language_code: Swift.String,
                owner_username: Swift.String,
                set_code: Swift.String
            ) {
                self.collector_number = collector_number
                self.foil = foil
                self.language_code = language_code
                self.owner_username = owner_username
                self.set_code = set_code
            }
            public enum CodingKeys: String, CodingKey {
                case collector_number
                case foil
                case language_code
                case owner_username
                case set_code
            }
        }
        /// - Remark: Generated from `#/components/schemas/SetInfoResponse`.
        public struct SetInfoResponse: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/SetInfoResponse/code`.
            public var code: Swift.String
            /// - Remark: Generated from `#/components/schemas/SetInfoResponse/name`.
            public var name: Swift.String
            /// Creates a new `SetInfoResponse`.
            ///
            /// - Parameters:
            ///   - code:
            ///   - name:
            public init(
                code: Swift.String,
                name: Swift.String
            ) {
                self.code = code
                self.name = name
            }
            public enum CodingKeys: String, CodingKey {
                case code
                case name
            }
        }
        /// - Remark: Generated from `#/components/schemas/SetRarityFilterRequest`.
        public struct SetRarityFilterRequest: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/SetRarityFilterRequest/is_open`.
            public var is_open: Swift.Bool
            /// Signed so out-of-range values (e.g. negative) fail domain validation with a clean 400
            /// instead of being rejected by the JSON extractor as a 422 before reaching the handler.
            ///
            /// - Remark: Generated from `#/components/schemas/SetRarityFilterRequest/kept_copies`.
            public var kept_copies: Swift.Int32
            /// - Remark: Generated from `#/components/schemas/SetRarityFilterRequest/rarity`.
            public var rarity: Swift.String
            /// Creates a new `SetRarityFilterRequest`.
            ///
            /// - Parameters:
            ///   - is_open:
            ///   - kept_copies: Signed so out-of-range values (e.g. negative) fail domain validation with a clean 400
            ///   - rarity:
            public init(
                is_open: Swift.Bool,
                kept_copies: Swift.Int32,
                rarity: Swift.String
            ) {
                self.is_open = is_open
                self.kept_copies = kept_copies
                self.rarity = rarity
            }
            public enum CodingKeys: String, CodingKey {
                case is_open
                case kept_copies
                case rarity
            }
        }
        /// - Remark: Generated from `#/components/schemas/SetVisibilityRequest`.
        public struct SetVisibilityRequest: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/SetVisibilityRequest/visibility`.
            public var visibility: Components.Schemas.CollectionVisibilityParam
            /// Creates a new `SetVisibilityRequest`.
            ///
            /// - Parameters:
            ///   - visibility:
            public init(visibility: Components.Schemas.CollectionVisibilityParam) {
                self.visibility = visibility
            }
            public enum CodingKeys: String, CodingKey {
                case visibility
            }
        }
        /// - Remark: Generated from `#/components/schemas/SortByParam`.
        @frozen public enum SortByParam: String, Codable, Hashable, Sendable, CaseIterable {
            case avg = "avg"
            case trend = "trend"
            case set_code = "set_code"
            case language_code = "language_code"
            case added_at = "added_at"
        }
        /// - Remark: Generated from `#/components/schemas/SortDirParam`.
        @frozen public enum SortDirParam: String, Codable, Hashable, Sendable, CaseIterable {
            case asc = "asc"
            case desc = "desc"
        }
        /// - Remark: Generated from `#/components/schemas/StatsResponse`.
        public struct StatsResponse: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/StatsResponse/card_number`.
            public var card_number: Swift.Int32
            /// - Remark: Generated from `#/components/schemas/StatsResponse/card_price_number`.
            public var card_price_number: Swift.Int32
            /// - Remark: Generated from `#/components/schemas/StatsResponse/db_size_mb`.
            public var db_size_mb: Swift.Int32
            /// Creates a new `StatsResponse`.
            ///
            /// - Parameters:
            ///   - card_number:
            ///   - card_price_number:
            ///   - db_size_mb:
            public init(
                card_number: Swift.Int32,
                card_price_number: Swift.Int32,
                db_size_mb: Swift.Int32
            ) {
                self.card_number = card_number
                self.card_price_number = card_price_number
                self.db_size_mb = db_size_mb
            }
            public enum CodingKeys: String, CodingKey {
                case card_number
                case card_price_number
                case db_size_mb
            }
        }
        /// - Remark: Generated from `#/components/schemas/TradeBindersResponse`.
        public struct TradeBindersResponse: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/TradeBindersResponse/binders`.
            public var binders: [Swift.String]
            /// Creates a new `TradeBindersResponse`.
            ///
            /// - Parameters:
            ///   - binders:
            public init(binders: [Swift.String]) {
                self.binders = binders
            }
            public enum CodingKeys: String, CodingKey {
                case binders
            }
        }
        /// One card offered in a trade, from either side. Which side it's on is conveyed by which of
        /// `TradeDetailResponse::my_cards`/`partner_cards` it's found in, not by a field here.
        ///
        /// - Remark: Generated from `#/components/schemas/TradeCardResponse`.
        public struct TradeCardResponse: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/TradeCardResponse/collector_number`.
            public var collector_number: Swift.String
            /// - Remark: Generated from `#/components/schemas/TradeCardResponse/foil`.
            public var foil: Swift.Bool
            /// - Remark: Generated from `#/components/schemas/TradeCardResponse/language_code`.
            public var language_code: Swift.String
            /// - Remark: Generated from `#/components/schemas/TradeCardResponse/name`.
            public var name: Swift.String
            /// - Remark: Generated from `#/components/schemas/TradeCardResponse/price_guide`.
            public var price_guide: Components.Schemas.PriceGuideResponse?
            /// - Remark: Generated from `#/components/schemas/TradeCardResponse/quantity`.
            public var quantity: Swift.Int32
            /// - Remark: Generated from `#/components/schemas/TradeCardResponse/scryfall_id`.
            public var scryfall_id: Swift.String
            /// - Remark: Generated from `#/components/schemas/TradeCardResponse/set_code`.
            public var set_code: Swift.String
            /// - Remark: Generated from `#/components/schemas/TradeCardResponse/the_gatherer_id`.
            public var the_gatherer_id: Swift.String?
            /// Creates a new `TradeCardResponse`.
            ///
            /// - Parameters:
            ///   - collector_number:
            ///   - foil:
            ///   - language_code:
            ///   - name:
            ///   - price_guide:
            ///   - quantity:
            ///   - scryfall_id:
            ///   - set_code:
            ///   - the_gatherer_id:
            public init(
                collector_number: Swift.String,
                foil: Swift.Bool,
                language_code: Swift.String,
                name: Swift.String,
                price_guide: Components.Schemas.PriceGuideResponse? = nil,
                quantity: Swift.Int32,
                scryfall_id: Swift.String,
                set_code: Swift.String,
                the_gatherer_id: Swift.String? = nil
            ) {
                self.collector_number = collector_number
                self.foil = foil
                self.language_code = language_code
                self.name = name
                self.price_guide = price_guide
                self.quantity = quantity
                self.scryfall_id = scryfall_id
                self.set_code = set_code
                self.the_gatherer_id = the_gatherer_id
            }
            public enum CodingKeys: String, CodingKey {
                case collector_number
                case foil
                case language_code
                case name
                case price_guide
                case quantity
                case scryfall_id
                case set_code
                case the_gatherer_id
            }
        }
        /// - Remark: Generated from `#/components/schemas/TradeDetailResponse`.
        public struct TradeDetailResponse: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/TradeDetailResponse/id`.
            public var id: Swift.String
            /// - Remark: Generated from `#/components/schemas/TradeDetailResponse/me`.
            public var me: Components.Schemas.TradePartyStateResponse
            /// - Remark: Generated from `#/components/schemas/TradeDetailResponse/my_cards`.
            public var my_cards: [Components.Schemas.TradeCardResponse]
            /// - Remark: Generated from `#/components/schemas/TradeDetailResponse/partner`.
            public var partner: Components.Schemas.TradePartyStateResponse
            /// - Remark: Generated from `#/components/schemas/TradeDetailResponse/partner_cards`.
            public var partner_cards: [Components.Schemas.TradeCardResponse]
            /// - Remark: Generated from `#/components/schemas/TradeDetailResponse/partner_username`.
            public var partner_username: Swift.String
            /// - Remark: Generated from `#/components/schemas/TradeDetailResponse/status`.
            public var status: Swift.String
            /// Creates a new `TradeDetailResponse`.
            ///
            /// - Parameters:
            ///   - id:
            ///   - me:
            ///   - my_cards:
            ///   - partner:
            ///   - partner_cards:
            ///   - partner_username:
            ///   - status:
            public init(
                id: Swift.String,
                me: Components.Schemas.TradePartyStateResponse,
                my_cards: [Components.Schemas.TradeCardResponse],
                partner: Components.Schemas.TradePartyStateResponse,
                partner_cards: [Components.Schemas.TradeCardResponse],
                partner_username: Swift.String,
                status: Swift.String
            ) {
                self.id = id
                self.me = me
                self.my_cards = my_cards
                self.partner = partner
                self.partner_cards = partner_cards
                self.partner_username = partner_username
                self.status = status
            }
            public enum CodingKeys: String, CodingKey {
                case id
                case me
                case my_cards
                case partner
                case partner_cards
                case partner_username
                case status
            }
        }
        /// One party's acceptance/confirmation/rating state, already resolved from the caller's point
        /// of view (`me` vs `partner`) — see `TradeDetailResponse`.
        ///
        /// - Remark: Generated from `#/components/schemas/TradePartyStateResponse`.
        public struct TradePartyStateResponse: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/TradePartyStateResponse/accepted`.
            public var accepted: Swift.Bool
            /// - Remark: Generated from `#/components/schemas/TradePartyStateResponse/confirmed`.
            public var confirmed: Swift.Bool
            /// - Remark: Generated from `#/components/schemas/TradePartyStateResponse/rating`.
            public var rating: Swift.Int32?
            /// Creates a new `TradePartyStateResponse`.
            ///
            /// - Parameters:
            ///   - accepted:
            ///   - confirmed:
            ///   - rating:
            public init(
                accepted: Swift.Bool,
                confirmed: Swift.Bool,
                rating: Swift.Int32? = nil
            ) {
                self.accepted = accepted
                self.confirmed = confirmed
                self.rating = rating
            }
            public enum CodingKeys: String, CodingKey {
                case accepted
                case confirmed
                case rating
            }
        }
        /// Status filter values for `GET /trades`, repeated for multiple statuses
        /// (e.g. `?status=PENDING&status=CLOSED`), mirroring `RarityCodeParam` on `/search/card`.
        ///
        /// - Remark: Generated from `#/components/schemas/TradeStatusParam`.
        @frozen public enum TradeStatusParam: String, Codable, Hashable, Sendable, CaseIterable {
            case PENDING = "PENDING"
            case ONE_ACCEPTED = "ONE_ACCEPTED"
            case FULLY_ACCEPTED = "FULLY_ACCEPTED"
            case COMPLETED = "COMPLETED"
            case CLOSED = "CLOSED"
            case ABANDONED = "ABANDONED"
        }
        /// - Remark: Generated from `#/components/schemas/TradeSummaryResponse`.
        public struct TradeSummaryResponse: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/TradeSummaryResponse/id`.
            public var id: Swift.String
            /// - Remark: Generated from `#/components/schemas/TradeSummaryResponse/my_card_count`.
            public var my_card_count: Swift.Int32
            /// - Remark: Generated from `#/components/schemas/TradeSummaryResponse/partner_card_count`.
            public var partner_card_count: Swift.Int32
            /// - Remark: Generated from `#/components/schemas/TradeSummaryResponse/partner_username`.
            public var partner_username: Swift.String
            /// - Remark: Generated from `#/components/schemas/TradeSummaryResponse/status`.
            public var status: Swift.String
            /// RFC 3339 timestamp
            ///
            /// - Remark: Generated from `#/components/schemas/TradeSummaryResponse/updated_at`.
            public var updated_at: Swift.String
            /// Creates a new `TradeSummaryResponse`.
            ///
            /// - Parameters:
            ///   - id:
            ///   - my_card_count:
            ///   - partner_card_count:
            ///   - partner_username:
            ///   - status:
            ///   - updated_at: RFC 3339 timestamp
            public init(
                id: Swift.String,
                my_card_count: Swift.Int32,
                partner_card_count: Swift.Int32,
                partner_username: Swift.String,
                status: Swift.String,
                updated_at: Swift.String
            ) {
                self.id = id
                self.my_card_count = my_card_count
                self.partner_card_count = partner_card_count
                self.partner_username = partner_username
                self.status = status
                self.updated_at = updated_at
            }
            public enum CodingKeys: String, CodingKey {
                case id
                case my_card_count
                case partner_card_count
                case partner_username
                case status
                case updated_at
            }
        }
        /// - Remark: Generated from `#/components/schemas/UserProfileResponse`.
        public struct UserProfileResponse: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/UserProfileResponse/avatar_url`.
            public var avatar_url: Swift.String?
            /// - Remark: Generated from `#/components/schemas/UserProfileResponse/id`.
            public var id: Swift.String
            /// - Remark: Generated from `#/components/schemas/UserProfileResponse/username`.
            public var username: Swift.String?
            /// Creates a new `UserProfileResponse`.
            ///
            /// - Parameters:
            ///   - avatar_url:
            ///   - id:
            ///   - username:
            public init(
                avatar_url: Swift.String? = nil,
                id: Swift.String,
                username: Swift.String? = nil
            ) {
                self.avatar_url = avatar_url
                self.id = id
                self.username = username
            }
            public enum CodingKeys: String, CodingKey {
                case avatar_url
                case id
                case username
            }
        }
        /// A suggested user only appears if they offer at least one card to trade — a `private` user,
        /// or one offering nothing under their current visibility/binders/rarity filters, is never
        /// suggested.
        ///
        /// - Remark: Generated from `#/components/schemas/UserSuggestionResponse`.
        public struct UserSuggestionResponse: Codable, Hashable, Sendable {
            /// Sum of the quantities this user actually offers to trade across their whole collection —
            /// not their total collection size.
            ///
            /// - Remark: Generated from `#/components/schemas/UserSuggestionResponse/card_count`.
            public var card_count: Swift.Int64
            /// Always 5 — hardcoded display value, not backed by any stored rating yet.
            ///
            /// - Remark: Generated from `#/components/schemas/UserSuggestionResponse/note`.
            public var note: Swift.Int32
            /// - Remark: Generated from `#/components/schemas/UserSuggestionResponse/username`.
            public var username: Swift.String
            /// Creates a new `UserSuggestionResponse`.
            ///
            /// - Parameters:
            ///   - card_count: Sum of the quantities this user actually offers to trade across their whole collection —
            ///   - note: Always 5 — hardcoded display value, not backed by any stored rating yet.
            ///   - username:
            public init(
                card_count: Swift.Int64,
                note: Swift.Int32,
                username: Swift.String
            ) {
                self.card_count = card_count
                self.note = note
                self.username = username
            }
            public enum CodingKeys: String, CodingKey {
                case card_count
                case note
                case username
            }
        }
        /// - Remark: Generated from `#/components/schemas/VisibilityResponse`.
        public struct VisibilityResponse: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/VisibilityResponse/visibility`.
            public var visibility: Components.Schemas.CollectionVisibilityParam
            /// Creates a new `VisibilityResponse`.
            ///
            /// - Parameters:
            ///   - visibility:
            public init(visibility: Components.Schemas.CollectionVisibilityParam) {
                self.visibility = visibility
            }
            public enum CodingKeys: String, CodingKey {
                case visibility
            }
        }
    }
}
